[build]
  command = "npm run build"
  publish = ".next"
  node_bundler = "esbuild"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://omclgnycoktwuuiuultx.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tY2xnbnljb2t0d3V1aXV1bHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjY3MTEsImV4cCI6MjA1OTM0MjcxMX0._P4z7ezWofbrpeNRlZlQ4Yb5sSdvHEON9vI0AFlcnmg"
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
